[package]
name = "playback"
version = "1.0.0"
authors = ["Rodrigo CÃ©sar de Freitas Dias <rcesar@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
winsafe = { git = "https://github.com/rodrigocfd/winsafe", features = ["dshow", "gui", "mf"] }
